### ISSUE TITLE
Your source of data doesn't work

### ISSUE THREAD

**Issue by adelbeke** [staticGuru/react_native_youtube_streamer#1]
`https://yt2html5.com/?id=A3hgVGFxZbg` returns `{"success":true,"data":{}}`.
So your package couldn't work :/

**Comment by staticGuru** [comment]
Hi @adscud 
Your report of the bug is greatly appreciated.

A bug was fixed and the issues were resolved. 
With _react_native_youtube_streamer@2.0.0_, you can render custom YouTube videos.

Happy coding !!!
